# 파이썬 리스트를 통해 Numpy Array 생성

In [1]:
import numpy as np

In [3]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [5]:
type(array1)

numpy.ndarray

In [6]:
array1.shape

(11,)

In [7]:
array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [8]:
array2.shape

(3, 4)

In [9]:
type(array2)
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
array1.size

11

In [11]:
array2.size

12

# 균일한 값으로 생성 ( full method )

In [12]:
array1 = np.full(6,7)

In [13]:
array1

array([7, 7, 7, 7, 7, 7])

In [14]:
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

# 모든 값이 0인 numpy array 생성

In [15]:
np.full(6, 0)

array([0, 0, 0, 0, 0, 0])

In [16]:
np.zeros(6, dtype=int)

array([0, 0, 0, 0, 0, 0])

# 모든 값이 1인 numpy array 생성

In [17]:
np.full(6, 1)

array([1, 1, 1, 1, 1, 1])

In [18]:
np.ones(6, dtype=int)

array([1, 1, 1, 1, 1, 1])

# 랜덤한 값들로 생성

In [19]:
array1 = np.random.random(6)
array2 = np.random.random(6)
print(array1)
print()
print(array2)

[0.66747309 0.61966624 0.17360468 0.03475049 0.73695464 0.75999927]

[0.82677699 0.18007568 0.38700323 0.45662107 0.376775   0.28128059]


# 연속된 값들이 담긴 numpy array 생성 ( numpy 모듈의 arange )
## 1. 파라미터 1개

In [20]:
array1 = np.arange(6)
print(array1)

[0 1 2 3 4 5]


## 2. 파라미터 2개

In [21]:
array1 = np.arange(2,7)
print(array1)

[2 3 4 5 6]


## 3. 파라미터 3개

In [22]:
array1 = np.arange(3, 17, 3)
print(array1)

[ 3  6  9 12 15]


# 인덱싱, 슬라이싱

## 인덱싱

In [24]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [25]:
array1[0]

2

In [26]:
array1[2]

5

In [27]:
array1[-1]

31

In [28]:
array1[-2]

29

In [29]:
array1[[1,3,4]]

array([ 3,  7, 11])

In [30]:
array2 = np.array([2, 1, 3])

In [31]:
array1[array2]

array([5, 3, 7])

## 슬라이싱

In [32]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [33]:
array1[0:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [34]:
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [35]:
array1[2:]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [36]:
array1[2:11:2]

array([ 5, 11, 17, 23, 31])

In [37]:
array1[2:11:3]

array([ 5, 13, 23])

# numpy 기본 연산

In [38]:
array1 = np.arange(10)
array2 = np.arange(10,20)

In [39]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [43]:
array1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
array1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [45]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
array1 = array1 * 2

In [47]:
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
array1 = np.arange(10)
array2 = np.arange(10,20)

In [49]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [50]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [51]:
array1 / array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

# numpy boolean 연산

In [52]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [53]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [56]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [57]:
booleans = np.array([True, True, False, True, True, False, True, True, True, False, True])

In [58]:
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

In [60]:
np.where(array1 > 4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [61]:
filter = np.where(array1 > 4)

In [63]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

# 최대값, 최소값

In [64]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

In [68]:
print(np.max(array1))
print(np.min(array1))

31
5


# 평균값

In [69]:
print(np.mean(array1))

15.25


# 중앙값

In [74]:
array1 = np.array([8, 12, 9, 15, 16])
array2 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(np.median(array1))
print(np.median(array2))

12.0
13.5



# 표준편차, 분산

In [76]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])
print(np.std(array1))
print(np.var(array1))

8.496322733983215
72.1875
